In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('dataset_diabetes_diabetic_data.csv')

In [3]:
df.head(10)

patient_nbr             race  gender       age  admission_type_id  \
0      8222157        Caucasian  Female    [0-10)                  6   
1     55629189        Caucasian  Female   [10-20)                  1   
2     86047875  AfricanAmerican  Female   [20-30)                  1   
3     82442376        Caucasian    Male   [30-40)                  1   
4     42519267        Caucasian    Male   [40-50)                  1   
5     82637451        Caucasian    Male   [50-60)                  2   
6     84259809        Caucasian    Male   [60-70)                  3   
7    114882984        Caucasian    Male   [70-80)                  1   
8     48330783        Caucasian  Female   [80-90)                  2   
9     63555939        Caucasian  Female  [90-100)                  3   

   discharge_disposition_id  admission_source_id  time_in_hospital  \
0                        25                    1                 1   
1                         1                    7                 3   
2                         1                    7                 2   
3                         1                    7                 2   
4                         1                    7                 1   
5                         1                    2                 3   
6                         1                    2                 4   
7                         1                    7                 5   
8                         1                    4                13   
9                         3                    4                12   

   num_lab_procedures  num_procedures  num_medications  number_outpatient  \
0                  41               0                1                  0   
1                  59               0               18                  0   
2                  11               5               13                  2   
3                  44               1               16                  0   
4                  51               0                8                  0   
5                  31               6               16                  0   
6                  70               1               21                  0   
7                  73               0               12                  0   
8                  68               2               28                  0   
9                  33               3               18                  0   

   number_emergency  number_inpatient  diag_1  diag_2 diag_3  \
0                 0                 0  250.83       ?      ?   
1                 0                 0     276  250.01    255   
2                 0                 1     648     250    V27   
3                 0                 0       8  250.43    403   
4                 0                 0     197     157    250   
5                 0                 0     414     411    250   
6                 0                 0     414     411    V45   
7                 0                 0     428     492    250   
8                 0                 0     398     427     38   
9                 0                 0     434     198    486   

   number_diagnoses change diabatic  
0                 1     No       No  
1                 9     Ch      Yes  
2                 6     No      Yes  
3                 7     Ch      Yes  
4                 5     Ch      Yes  
5                 9     No      Yes  
6                 7     Ch      Yes  
7                 8     No      Yes  
8                 8     Ch      Yes  
9                 8     Ch      Yes

In [4]:
df.drop(columns='patient_nbr',inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70180 entries, 0 to 70179
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   race                      70180 non-null  object
 1   gender                    70180 non-null  object
 2   age                       70180 non-null  object
 3   admission_type_id         70180 non-null  int64 
 4   discharge_disposition_id  70180 non-null  int64 
 5   admission_source_id       70180 non-null  int64 
 6   time_in_hospital          70180 non-null  int64 
 7   num_lab_procedures        70180 non-null  int64 
 8   num_procedures            70180 non-null  int64 
 9   num_medications           70180 non-null  int64 
 10  number_outpatient         70180 non-null  int64 
 11  number_emergency          70180 non-null  int64 
 12  number_inpatient          70180 non-null  int64 
 13  diag_1                    70180 non-null  object
 14  diag_2                

In [6]:
df.shape

(70180, 19)

In [7]:
df.nunique()

race                          6
gender                        3
age                          10
admission_type_id             8
discharge_disposition_id     26
admission_source_id          13
time_in_hospital             14
num_lab_procedures          116
num_procedures                7
num_medications              74
number_outpatient            29
number_emergency             19
number_inpatient             21
diag_1                      685
diag_2                      702
diag_3                      727
number_diagnoses             16
change                        2
diabatic                      2
dtype: int64

In [8]:
df[df['diag_1']=='?'].value_counts().sum()

19

In [9]:
df[df['diag_2']=='?'].value_counts().sum()

304

In [10]:
df[df['diag_3']=='?'].value_counts().sum()

1237

In [129]:
df1['race'].value_counts()['?']

1461

In [11]:
df1 = df.drop(columns='diag_1')

In [12]:
df1 = df1.drop(columns='diag_2')
df1 = df1.drop(columns='diag_3')

In [13]:
df1.head()

race  gender      age  admission_type_id  \
0        Caucasian  Female   [0-10)                  6   
1        Caucasian  Female  [10-20)                  1   
2  AfricanAmerican  Female  [20-30)                  1   
3        Caucasian    Male  [30-40)                  1   
4        Caucasian    Male  [40-50)                  1   

   discharge_disposition_id  admission_source_id  time_in_hospital  \
0                        25                    1                 1   
1                         1                    7                 3   
2                         1                    7                 2   
3                         1                    7                 2   
4                         1                    7                 1   

   num_lab_procedures  num_procedures  num_medications  number_outpatient  \
0                  41               0                1                  0   
1                  59               0               18                  0   
2                  11               5               13                  2   
3                  44               1               16                  0   
4                  51               0                8                  0   

   number_emergency  number_inpatient  number_diagnoses change diabatic  
0                 0                 0                 1     No       No  
1                 0                 0                 9     Ch      Yes  
2                 0                 1                 6     No      Yes  
3                 0                 0                 7     Ch      Yes  
4                 0                 0                 5     Ch      Yes

In [14]:
df.shape

(70180, 19)

In [15]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
70175    False
70176    False
70177    False
70178    False
70179    False
Length: 70180, dtype: bool

In [16]:
df.shape

(70180, 19)

In [17]:
dups = df1.duplicated()

In [18]:
df1[df1.select_dtypes(['object']).columns] = df1.select_dtypes(['object']).apply(lambda x: x.astype('category'))

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70180 entries, 0 to 70179
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype   
---  ------                    --------------  -----   
 0   race                      70180 non-null  category
 1   gender                    70180 non-null  category
 2   age                       70180 non-null  category
 3   admission_type_id         70180 non-null  int64   
 4   discharge_disposition_id  70180 non-null  int64   
 5   admission_source_id       70180 non-null  int64   
 6   time_in_hospital          70180 non-null  int64   
 7   num_lab_procedures        70180 non-null  int64   
 8   num_procedures            70180 non-null  int64   
 9   num_medications           70180 non-null  int64   
 10  number_outpatient         70180 non-null  int64   
 11  number_emergency          70180 non-null  int64   
 12  number_inpatient          70180 non-null  int64   
 13  number_diagnoses          70180 non-null  int6

In [20]:
df1.head()

race  gender      age  admission_type_id  \
0        Caucasian  Female   [0-10)                  6   
1        Caucasian  Female  [10-20)                  1   
2  AfricanAmerican  Female  [20-30)                  1   
3        Caucasian    Male  [30-40)                  1   
4        Caucasian    Male  [40-50)                  1   

   discharge_disposition_id  admission_source_id  time_in_hospital  \
0                        25                    1                 1   
1                         1                    7                 3   
2                         1                    7                 2   
3                         1                    7                 2   
4                         1                    7                 1   

   num_lab_procedures  num_procedures  num_medications  number_outpatient  \
0                  41               0                1                  0   
1                  59               0               18                  0   
2                  11               5               13                  2   
3                  44               1               16                  0   
4                  51               0                8                  0   

   number_emergency  number_inpatient  number_diagnoses change diabatic  
0                 0                 0                 1     No       No  
1                 0                 0                 9     Ch      Yes  
2                 0                 1                 6     No      Yes  
3                 0                 0                 7     Ch      Yes  
4                 0                 0                 5     Ch      Yes

In [22]:
x = df1.iloc[:,:-1]

In [23]:
y = df1.iloc[:,-1]

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [25]:
x_train.head()

race  gender      age  admission_type_id  \
66671  AfricanAmerican  Female  [50-60)                  1   
4429         Caucasian    Male  [70-80)                  5   
16083        Caucasian  Female  [80-90)                  2   
35178        Caucasian  Female  [60-70)                  2   
45390        Caucasian  Female  [70-80)                  1   

       discharge_disposition_id  admission_source_id  time_in_hospital  \
66671                         1                    7                 2   
4429                         11                   17                 9   
16083                         6                    6                 9   
35178                         1                    1                 6   
45390                         1                    7                 6   

       num_lab_procedures  num_procedures  num_medications  number_outpatient  \
66671                  72               1               18                  0   
4429                   23               0               18                  0   
16083                  63               0               17                  0   
35178                  28               5               10                  0   
45390                  35               1               22                  3   

       number_emergency  number_inpatient  number_diagnoses change  
66671                 0                 0                 9     No  
4429                  1                 0                 5     No  
16083                 0                 0                 9     No  
35178                 0                 0                 5     No  
45390                 0                 1                 9     No

In [26]:
x_test.head()

race  gender      age  admission_type_id  \
50590        Caucasian  Female  [60-70)                  3   
1610         Caucasian    Male  [50-60)                  1   
40415        Caucasian    Male  [70-80)                  1   
41496  AfricanAmerican    Male  [60-70)                  3   
51050  AfricanAmerican    Male  [40-50)                  1   

       discharge_disposition_id  admission_source_id  time_in_hospital  \
50590                         1                    1                 4   
1610                          3                    7                10   
40415                         1                    7                 1   
41496                         1                    1                 4   
51050                         1                    7                 2   

       num_lab_procedures  num_procedures  num_medications  number_outpatient  \
50590                  42               0               11                  3   
1610                   81               6               22                  0   
40415                  44               0               11                  0   
41496                  36               2               21                  0   
51050                  34               0                4                  0   

       number_emergency  number_inpatient  number_diagnoses change  
50590                 0                 0                 5     Ch  
1610                  0                 1                 9     Ch  
40415                 0                 0                 5     Ch  
41496                 1                 5                 9     Ch  
51050                 3                 3                 6     Ch

In [90]:
df1.shape

(70180, 16)

In [27]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [28]:
transform = ColumnTransformer(transformers=[('on',OneHotEncoder(drop = 'first' , sparse=False,dtype='int64'),['race','age','gender','change'])],remainder='passthrough')

In [29]:
x_train = transform.fit_transform(x_train)

In [30]:
x_test=transform.transform(x_test)

# Logistic Regression


In [31]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

D:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [33]:
y_pred = classifier.predict(x_test)

Confusion metrics

In [55]:
from sklearn.metrics import confusion_matrix , accuracy_score , auc ,classification_report

In [36]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[3819, 2056],
       [2705, 8965]], dtype=int64)

Accuracy score

In [38]:
accuracy_score(y_test , y_pred)

0.7286406383585067

AUC Score

In [39]:
from sklearn import metrics

In [42]:
log = classifier.predict_proba(x_test)

In [45]:
log = log[:,1]

In [46]:
auc =  metrics.roc_auc_score(y_test,log)

In [47]:
auc

0.8184535944137542

Classification Report

In [58]:
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

          No       0.59      0.65      0.62      5875
         Yes       0.81      0.77      0.79     11670

    accuracy                           0.73     17545
   macro avg       0.70      0.71      0.70     17545
weighted avg       0.74      0.73      0.73     17545



# Decision Tree

In [49]:
from sklearn.tree import DecisionTreeClassifier
model2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
model2.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [53]:
y_pred2 = model2.predict(x_test)

Confusion metrics

In [54]:
cm = confusion_matrix(y_test,y_pred2)
cm

array([[3311, 2564],
       [2441, 9229]], dtype=int64)

In [60]:
log2 = model2.predict_proba(x_test)
log2 = log2[:,1]
auc =  metrics.roc_auc_score(y_test,log2)
auc

0.6771913726777151

Accuracy score

In [61]:
accuracy_score(y_test , y_pred2)

0.7147335423197492

Classification Report

In [62]:
cr = classification_report(y_test,y_pred2)
print(cr)

              precision    recall  f1-score   support

          No       0.58      0.56      0.57      5875
         Yes       0.78      0.79      0.79     11670

    accuracy                           0.71     17545
   macro avg       0.68      0.68      0.68     17545
weighted avg       0.71      0.71      0.71     17545



Feature Importance

In [88]:
from sklearn.datasets import make_classification


In [93]:
x,y = make_classification(n_samples=1000 , n_classes=2 , n_features=2 , n_informative=2 , n_redundant=0 , random_state=0)

In [94]:
cl = DecisionTreeClassifier()

In [95]:
cl.fit(x,y)

DecisionTreeClassifier()

In [96]:
cl.feature_importances_

array([0.1011357, 0.8988643])

# Random Forest

In [64]:
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
model3.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [68]:
y_pred3 = model3.predict(x_test)

Confusion metrics

In [69]:
cm = confusion_matrix(y_test,y_pred3)
cm

array([[4054, 1821],
       [2912, 8758]], dtype=int64)

AUC Score

In [71]:
log3 = model3.predict_proba(x_test)
log3 = log3[:,1]
auc =  metrics.roc_auc_score(y_test,log3)
auc

0.8164984521139858

Accuracy score

In [72]:
accuracy_score(y_test , y_pred3)

0.7302365346252494

classification report

In [87]:
cr = classification_report(y_test,y_pred3)
print(cr)

              precision    recall  f1-score   support

          No       0.58      0.69      0.63      5875
         Yes       0.83      0.75      0.79     11670

    accuracy                           0.73     17545
   macro avg       0.70      0.72      0.71     17545
weighted avg       0.75      0.73      0.74     17545



# DecisionTree using GridSearchCV

In [75]:
from sklearn.model_selection import GridSearchCV

param_grid = {'max_features': ['auto', 'sqrt', 'log2'],
              'ccp_alpha': [0.1, .01, .001],
              'max_depth' : [5, 6, 7, 8, 9],
              'criterion' :['gini', 'entropy']
             }


In [76]:
dec = DecisionTreeClassifier(random_state=0)
grid = GridSearchCV(estimator=dec , param_grid=param_grid , cv=5 , verbose=True)

In [77]:
grid.fit(x_train , y_train)

Fitting 5 folds for each of 90 candidates, totalling 450 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'ccp_alpha': [0.1, 0.01, 0.001],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 6, 7, 8, 9],
                         'max_features': ['auto', 'sqrt', 'log2']},
             verbose=True)

In [78]:
model4 = grid.best_estimator_

In [79]:
y_pred4 = model4.predict(x_test)

Confusion metrics

In [80]:
cm = confusion_matrix(y_test,y_pred4)
cm

array([[5853,   22],
       [5116, 6554]], dtype=int64)

AUC Score

In [81]:
log4 = model4.predict_proba(x_test)
log4 = log4[:,1]
auc =  metrics.roc_auc_score(y_test,log4)
auc

0.7898037156557094

Accuracy score

In [85]:
accuracy_score(y_test , y_pred4)

0.7071530350527215

classification report

In [86]:
cr = classification_report(y_test,y_pred4)
print(cr)

              precision    recall  f1-score   support

          No       0.53      1.00      0.69      5875
         Yes       1.00      0.56      0.72     11670

    accuracy                           0.71     17545
   macro avg       0.77      0.78      0.71     17545
weighted avg       0.84      0.71      0.71     17545

