In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('dataset_diabetes_diabetic_data.csv')

In [3]:
df.head(10)

patient_nbr             race  gender       age  admission_type_id  \
0      8222157        Caucasian  Female    [0-10)                  6   
1     55629189        Caucasian  Female   [10-20)                  1   
2     86047875  AfricanAmerican  Female   [20-30)                  1   
3     82442376        Caucasian    Male   [30-40)                  1   
4     42519267        Caucasian    Male   [40-50)                  1   
5     82637451        Caucasian    Male   [50-60)                  2   
6     84259809        Caucasian    Male   [60-70)                  3   
7    114882984        Caucasian    Male   [70-80)                  1   
8     48330783        Caucasian  Female   [80-90)                  2   
9     63555939        Caucasian  Female  [90-100)                  3   

   discharge_disposition_id  admission_source_id  time_in_hospital  \
0                        25                    1                 1   
1                         1                    7                 3   
2                         1                    7                 2   
3                         1                    7                 2   
4                         1                    7                 1   
5                         1                    2                 3   
6                         1                    2                 4   
7                         1                    7                 5   
8                         1                    4                13   
9                         3                    4                12   

   num_lab_procedures  num_procedures  num_medications  number_outpatient  \
0                  41               0                1                  0   
1                  59               0               18                  0   
2                  11               5               13                  2   
3                  44               1               16                  0   
4                  51               0                8                  0   
5                  31               6               16                  0   
6                  70               1               21                  0   
7                  73               0               12                  0   
8                  68               2               28                  0   
9                  33               3               18                  0   

   number_emergency  number_inpatient  diag_1  diag_2 diag_3  \
0                 0                 0  250.83       ?      ?   
1                 0                 0     276  250.01    255   
2                 0                 1     648     250    V27   
3                 0                 0       8  250.43    403   
4                 0                 0     197     157    250   
5                 0                 0     414     411    250   
6                 0                 0     414     411    V45   
7                 0                 0     428     492    250   
8                 0                 0     398     427     38   
9                 0                 0     434     198    486   

   number_diagnoses change diabatic  
0                 1     No       No  
1                 9     Ch      Yes  
2                 6     No      Yes  
3                 7     Ch      Yes  
4                 5     Ch      Yes  
5                 9     No      Yes  
6                 7     Ch      Yes  
7                 8     No      Yes  
8                 8     Ch      Yes  
9                 8     Ch      Yes

In [4]:
df.drop(columns='patient_nbr',inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70180 entries, 0 to 70179
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   race                      70180 non-null  object
 1   gender                    70180 non-null  object
 2   age                       70180 non-null  object
 3   admission_type_id         70180 non-null  int64 
 4   discharge_disposition_id  70180 non-null  int64 
 5   admission_source_id       70180 non-null  int64 
 6   time_in_hospital          70180 non-null  int64 
 7   num_lab_procedures        70180 non-null  int64 
 8   num_procedures            70180 non-null  int64 
 9   num_medications           70180 non-null  int64 
 10  number_outpatient         70180 non-null  int64 
 11  number_emergency          70180 non-null  int64 
 12  number_inpatient          70180 non-null  int64 
 13  diag_1                    70180 non-null  object
 14  diag_2                

In [6]:
df.shape

(70180, 19)

In [7]:
df.nunique()

race                          6
gender                        3
age                          10
admission_type_id             8
discharge_disposition_id     26
admission_source_id          13
time_in_hospital             14
num_lab_procedures          116
num_procedures                7
num_medications              74
number_outpatient            29
number_emergency             19
number_inpatient             21
diag_1                      685
diag_2                      702
diag_3                      727
number_diagnoses             16
change                        2
diabatic                      2
dtype: int64

In [8]:
df[df['diag_1']=='?'].value_counts().sum()

19

In [9]:
df[df['diag_2']=='?'].value_counts().sum()

304

In [10]:
df[df['diag_3']=='?'].value_counts().sum()

1237

In [11]:
df['race'].value_counts()['?']

1461

In [12]:
df1 = df.drop(columns='diag_1')

In [13]:
df1 = df1.drop(columns='diag_2')
df1 = df1.drop(columns='diag_3')

In [14]:
df1.head()

race  gender      age  admission_type_id  \
0        Caucasian  Female   [0-10)                  6   
1        Caucasian  Female  [10-20)                  1   
2  AfricanAmerican  Female  [20-30)                  1   
3        Caucasian    Male  [30-40)                  1   
4        Caucasian    Male  [40-50)                  1   

   discharge_disposition_id  admission_source_id  time_in_hospital  \
0                        25                    1                 1   
1                         1                    7                 3   
2                         1                    7                 2   
3                         1                    7                 2   
4                         1                    7                 1   

   num_lab_procedures  num_procedures  num_medications  number_outpatient  \
0                  41               0                1                  0   
1                  59               0               18                  0   
2                  11               5               13                  2   
3                  44               1               16                  0   
4                  51               0                8                  0   

   number_emergency  number_inpatient  number_diagnoses change diabatic  
0                 0                 0                 1     No       No  
1                 0                 0                 9     Ch      Yes  
2                 0                 1                 6     No      Yes  
3                 0                 0                 7     Ch      Yes  
4                 0                 0                 5     Ch      Yes

In [15]:
df1.shape

(70180, 16)

In [16]:
df1.drop_duplicates(inplace=True)

In [17]:
df1.shape

(70158, 16)

In [18]:
df1[df1.select_dtypes(['object']).columns] = df1.select_dtypes(['object']).apply(lambda x: x.astype('category'))

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70158 entries, 0 to 70179
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype   
---  ------                    --------------  -----   
 0   race                      70158 non-null  category
 1   gender                    70158 non-null  category
 2   age                       70158 non-null  category
 3   admission_type_id         70158 non-null  int64   
 4   discharge_disposition_id  70158 non-null  int64   
 5   admission_source_id       70158 non-null  int64   
 6   time_in_hospital          70158 non-null  int64   
 7   num_lab_procedures        70158 non-null  int64   
 8   num_procedures            70158 non-null  int64   
 9   num_medications           70158 non-null  int64   
 10  number_outpatient         70158 non-null  int64   
 11  number_emergency          70158 non-null  int64   
 12  number_inpatient          70158 non-null  int64   
 13  number_diagnoses          70158 non-null  int6

In [20]:
df1.head()

race  gender      age  admission_type_id  \
0        Caucasian  Female   [0-10)                  6   
1        Caucasian  Female  [10-20)                  1   
2  AfricanAmerican  Female  [20-30)                  1   
3        Caucasian    Male  [30-40)                  1   
4        Caucasian    Male  [40-50)                  1   

   discharge_disposition_id  admission_source_id  time_in_hospital  \
0                        25                    1                 1   
1                         1                    7                 3   
2                         1                    7                 2   
3                         1                    7                 2   
4                         1                    7                 1   

   num_lab_procedures  num_procedures  num_medications  number_outpatient  \
0                  41               0                1                  0   
1                  59               0               18                  0   
2                  11               5               13                  2   
3                  44               1               16                  0   
4                  51               0                8                  0   

   number_emergency  number_inpatient  number_diagnoses change diabatic  
0                 0                 0                 1     No       No  
1                 0                 0                 9     Ch      Yes  
2                 0                 1                 6     No      Yes  
3                 0                 0                 7     Ch      Yes  
4                 0                 0                 5     Ch      Yes

In [21]:
x = df1.iloc[:,:-1]

In [22]:
y = df1.iloc[:,-1]

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [24]:
x_train.head()

race  gender      age  admission_type_id  \
4933         Caucasian  Female  [70-80)                  1   
39725        Caucasian    Male  [70-80)                  3   
23082        Caucasian    Male  [80-90)                  3   
22313  AfricanAmerican  Female  [40-50)                  1   
46770        Caucasian  Female  [50-60)                  3   

       discharge_disposition_id  admission_source_id  time_in_hospital  \
4933                          5                    7                13   
39725                        23                    1                 2   
23082                         6                    4                14   
22313                         1                    7                 2   
46770                         1                    1                 1   

       num_lab_procedures  num_procedures  num_medications  number_outpatient  \
4933                   54               3               31                  0   
39725                  38               1               13                  2   
23082                  50               1               21                  0   
22313                  47               1               14                  1   
46770                  42               2               24                  0   

       number_emergency  number_inpatient  number_diagnoses change  
4933                  0                 1                 8     No  
39725                 0                 0                 6     Ch  
23082                 0                 1                 9     No  
22313                 0                10                 9     No  
46770                 0                 3                 9     Ch

In [25]:
x_test.head()

race  gender      age  admission_type_id  \
46635  Caucasian    Male  [50-60)                  2   
30356  Caucasian    Male  [70-80)                  2   
57459  Caucasian    Male  [60-70)                  3   
38818  Caucasian  Female  [50-60)                  1   
7769   Caucasian    Male  [60-70)                  2   

       discharge_disposition_id  admission_source_id  time_in_hospital  \
46635                         1                    7                 1   
30356                         1                    1                 1   
57459                         1                    1                 3   
38818                        22                    7                 8   
7769                          1                    1                 5   

       num_lab_procedures  num_procedures  num_medications  number_outpatient  \
46635                  35               1               14                  0   
30356                  34               1                4                  0   
57459                  32               6               15                  0   
38818                  52               1               24                  0   
7769                   43               0               13                  0   

       number_emergency  number_inpatient  number_diagnoses change  
46635                 1                 3                 8     No  
30356                 0                 0                 4     Ch  
57459                 0                 1                 7     No  
38818                 1                 0                 7     Ch  
7769                  0                 0                 5     No

In [26]:
df1.shape

(70158, 16)

In [27]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [28]:
transform = ColumnTransformer(transformers=[('on',OneHotEncoder(drop = 'first' , sparse=False,dtype='int64'),['race','age','gender','change'])],remainder='passthrough')

In [29]:
x_train = transform.fit_transform(x_train)

In [30]:
x_test=transform.transform(x_test)

In [31]:
x_train

array([[0, 0, 1, ..., 0, 1, 8],
       [0, 0, 1, ..., 0, 0, 6],
       [0, 0, 1, ..., 0, 1, 9],
       ...,
       [1, 0, 0, ..., 0, 0, 9],
       [0, 0, 1, ..., 0, 0, 8],
       [0, 0, 1, ..., 0, 0, 9]], dtype=int64)

# Logistic Regression


In [32]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

D:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [33]:
y_pred = classifier.predict(x_test)

Confusion metrics

In [34]:
from sklearn.metrics import confusion_matrix , accuracy_score , auc ,classification_report

In [35]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[3943, 1872],
       [2734, 8991]], dtype=int64)

Accuracy score

In [36]:
accuracy_score(y_test , y_pred)

0.737400228050171

AUC Score

In [37]:
from sklearn import metrics

In [38]:
log = classifier.predict_proba(x_test)

In [39]:
log = log[:,1]

In [40]:
auc =  metrics.roc_auc_score(y_test,log)

In [41]:
auc

0.8263878616987534

Classification Report

In [42]:
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

          No       0.59      0.68      0.63      5815
         Yes       0.83      0.77      0.80     11725

    accuracy                           0.74     17540
   macro avg       0.71      0.72      0.71     17540
weighted avg       0.75      0.74      0.74     17540



# Decision Tree

In [43]:
from sklearn.tree import DecisionTreeClassifier
model2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
model2.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [44]:
y_pred2 = model2.predict(x_test)

Confusion metrics

In [45]:
cm = confusion_matrix(y_test,y_pred2)
cm

array([[3307, 2508],
       [2521, 9204]], dtype=int64)

In [46]:
log2 = model2.predict_proba(x_test)
log2 = log2[:,1]
auc =  metrics.roc_auc_score(y_test,log2)
auc

0.6768512504422978

Accuracy score

In [47]:
accuracy_score(y_test , y_pred2)

0.7132839224629418

Classification Report

In [48]:
cr = classification_report(y_test,y_pred2)
print(cr)

              precision    recall  f1-score   support

          No       0.57      0.57      0.57      5815
         Yes       0.79      0.78      0.79     11725

    accuracy                           0.71     17540
   macro avg       0.68      0.68      0.68     17540
weighted avg       0.71      0.71      0.71     17540



# Random Forest

In [49]:
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
model3.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [50]:
y_pred3 = model3.predict(x_test)

Confusion metrics

In [51]:
cm = confusion_matrix(y_test,y_pred3)
cm

array([[4104, 1711],
       [2946, 8779]], dtype=int64)

AUC Score

In [52]:
log3 = model3.predict_proba(x_test)
log3 = log3[:,1]
auc =  metrics.roc_auc_score(y_test,log3)
auc

0.8186647208619718

Accuracy score

In [53]:
accuracy_score(y_test , y_pred3)

0.7344925883694413

classification report

In [54]:
cr = classification_report(y_test,y_pred3)
print(cr)

              precision    recall  f1-score   support

          No       0.58      0.71      0.64      5815
         Yes       0.84      0.75      0.79     11725

    accuracy                           0.73     17540
   macro avg       0.71      0.73      0.71     17540
weighted avg       0.75      0.73      0.74     17540



# DecisionTree using GridSearchCV

In [55]:
from sklearn.model_selection import GridSearchCV

param_grid = {'max_features': ['auto', 'sqrt', 'log2'],
              'ccp_alpha': [0.1, .01, .001],
              'max_depth' : [5, 6, 7, 8, 9],
              'criterion' :['gini', 'entropy']
             }


In [56]:
dec = DecisionTreeClassifier(random_state=0)
grid = GridSearchCV(estimator=dec , param_grid=param_grid , cv=5 , verbose=True)

In [57]:
grid.fit(x_train , y_train)

Fitting 5 folds for each of 90 candidates, totalling 450 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=0),
             param_grid={'ccp_alpha': [0.1, 0.01, 0.001],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 6, 7, 8, 9],
                         'max_features': ['auto', 'sqrt', 'log2']},
             verbose=True)

In [58]:
model4 = grid.best_estimator_

In [59]:
y_pred4 = model4.predict(x_test)

Confusion metrics

In [60]:
cm = confusion_matrix(y_test,y_pred4)
cm

array([[4982,  833],
       [3960, 7765]], dtype=int64)

AUC Score

In [61]:
log4 = model4.predict_proba(x_test)
log4 = log4[:,1]
auc =  metrics.roc_auc_score(y_test,log4)
auc

0.8173680375911866

Accuracy score

In [62]:
accuracy_score(y_test , y_pred4)

0.726738882554162

classification report

In [63]:
cr = classification_report(y_test,y_pred4)
print(cr)

              precision    recall  f1-score   support

          No       0.56      0.86      0.68      5815
         Yes       0.90      0.66      0.76     11725

    accuracy                           0.73     17540
   macro avg       0.73      0.76      0.72     17540
weighted avg       0.79      0.73      0.73     17540

